/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoConverterRouteImport } from './routes/video-converter'
import { Route as ImageConverterRouteImport } from './routes/image-converter'
import { Route as DocumentConverterRouteImport } from './routes/document-converter'
import { Route as AudioConverterRouteImport } from './routes/audio-converter'
import { Route as IndexRouteImport } from './routes/index'

const VideoConverterRoute = VideoConverterRouteImport.update({
  id: '/video-converter',
  path: '/video-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageConverterRoute = ImageConverterRouteImport.update({
  id: '/image-converter',
  path: '/image-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentConverterRoute = DocumentConverterRouteImport.update({
  id: '/document-converter',
  path: '/document-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioConverterRoute = AudioConverterRouteImport.update({
  id: '/audio-converter',
  path: '/audio-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/document-converter': typeof DocumentConverterRoute
  '/image-converter': typeof ImageConverterRoute
  '/video-converter': typeof VideoConverterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/document-converter': typeof DocumentConverterRoute
  '/image-converter': typeof ImageConverterRoute
  '/video-converter': typeof VideoConverterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-converter': typeof AudioConverterRoute
  '/document-converter': typeof DocumentConverterRoute
  '/image-converter': typeof ImageConverterRoute
  '/video-converter': typeof VideoConverterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-converter'
    | '/document-converter'
    | '/image-converter'
    | '/video-converter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-converter'
    | '/document-converter'
    | '/image-converter'
    | '/video-converter'
  id:
    | '__root__'
    | '/'
    | '/audio-converter'
    | '/document-converter'
    | '/image-converter'
    | '/video-converter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioConverterRoute: typeof AudioConverterRoute
  DocumentConverterRoute: typeof DocumentConverterRoute
  ImageConverterRoute: typeof ImageConverterRoute
  VideoConverterRoute: typeof VideoConverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-converter': {
      id: '/video-converter'
      path: '/video-converter'
      fullPath: '/video-converter'
      preLoaderRoute: typeof VideoConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-converter': {
      id: '/image-converter'
      path: '/image-converter'
      fullPath: '/image-converter'
      preLoaderRoute: typeof ImageConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-converter': {
      id: '/document-converter'
      path: '/document-converter'
      fullPath: '/document-converter'
      preLoaderRoute: typeof DocumentConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-converter': {
      id: '/audio-converter'
      path: '/audio-converter'
      fullPath: '/audio-converter'
      preLoaderRoute: typeof AudioConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioConverterRoute: AudioConverterRoute,
  DocumentConverterRoute: DocumentConverterRoute,
  ImageConverterRoute: ImageConverterRoute,
  VideoConverterRoute: VideoConverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
